version: '3'
services:
  villagerdb:
    build:
      context: .
    container_name: villagerdb_app
    environment:
      - ELASTICSEARCH_CONNECT_STRING=http://villagerdb_es:9200
      - REDIS_CONNECT_STRING=redis://villagerdb_redis:6379/0
    restart: always
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: villagerdb_es
    environment:
      - node.name=villagerdb_es
      - cluster.name=villagerdb-es-cluster
      - cluster.initial_master_nodes=villagerdb_es
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - villagerdb_es:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  redis:
    container_name: villagerdb_redis
    image: redis:latest
    ports:
      - 6379:6379
  mongo:
    container_name: villagerdb_mongo
    image: mongo:4.2.3
    volumes:
      - villagerdb_mongo:/data/db
    ports:
      -  27017:27017
volumes:
  villagerdb_es:
    driver: local
  villagerdb_mongo:
    driver: local